FROM ubuntu:16.04

MAINTAINER Sergey Serebryakov <sergey.serebryakov@hpe.com>

RUN apt-get update && apt-get install -y --no-install-recommends \
        apt-utils \
        python-setuptools \
        build-essential \
        curl \
        git \
        libcurl3-dev \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        rsync \
        software-properties-common \
        unzip \
        zip \
        zlib1g-dev \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py

RUN rm -f /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python

# Better way to do it? This results in re-installing all python packages that takes time.
# RUN pip install -r /athena/requirements/python3.txt
RUN pip --no-cache-dir install \
    matplotlib==3.0.2 \
    h5py==2.9.0 \
    numpy==1.16.0 \
    scipy==1.2.0 \
    scikit-learn==0.20.2 \
    pandas==0.23.4 \
    future==0.17.1 \
    absl-py==0.7.0 \
    tensorboard==1.13.1 \
    tensorflow==1.13.1

